### ISSUE TITLE
runSpeed, stepper running backward with speed 0

### ISSUE THREAD

**Issue by dzufferey** [adafruit/AccelStepper#1]
I encountered the problem of having a stepper motor running backward instead of staying still when calling `runSpeed()` after `setSpeed(0)`.

I could  fix the problem by adding an additional check in the method `step0` at AccelStepper.cpp:215.
Instead of defaulting to backward, checking negative speed fixes it.
Here is the fix:

```
// 0 pin step function (ie for functional usage)
void AccelStepper::step0()
{
  if (_speed > 0) {
    _forward();
  } else if (_speed < 0) {
    _backward();
  }
}
```

**Comment by ladyada** [comment]
archiving this repo - and pointing people to http://www.airspayce.com/mikem/arduino/AccelStepper/
thanks :)
