### ISSUE TITLE
Fork far behind AccelStepper

### ISSUE THREAD

**Issue by Brideau** [adafruit/AccelStepper#2]
I was wondering if there is any plans to bring in all of the changes that have happened in AccelStepper since this was originally forked at v1.3? There's been 43 versions since, so it's trailing behind quite a bit. I am considering giving it a try myself, but it would take me considerably more time than somebody already familiar with the library.

**Comment by yeahlo** [comment]
any news?

**Comment by RangerPhoton** [comment]
Yes, this fork caused me some time tracking down a missing class before I realized it was obsolete.  
http://www.airspayce.com/mikem/arduino/AccelStepper/ now directly supports AdaFruit Motorshields!

**Comment by ladyada** [comment]
archiving this repo - and pointing people to http://www.airspayce.com/mikem/arduino/AccelStepper/
thanks :)
